
server:
  port: 11000

  
spring:
  application:
    name: ttc-order
  datasource:
    url: jdbc:h2:~/tmp/db/h2/tcc-user.h2;AUTO_SERVER=TRUE;MODE=MYSQL
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    data:
      - classpath:schema.sql
      - classpath:data.sql
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.show-sql: true
      hibernate.hbm2ddl.auto: update
    open-in-view: true