server:
  port: 10000

  
spring:
  application:
    name: ttc-order
  datasource:
    url: jdbc:h2:~/tmp/db/h2/tcc-tcc.h2;AUTO_SERVER=TRUE;MODE=MYSQL
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    data:
      - classpath:schema.sql
      - classpath:data.sql
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate.enable_lazy_load_no_trans: true
      hibernate.show-sql: true
      hibernate.hbm2ddl.auto: update
    open-in-view: true

log4j:
  logger:
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.hibernate.type.descriptor.sql: trace
logging:
  level:
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN

my:
  tcc:
    url: "http://localhost:10000"
  user:
    url : "http://localhost:11000"
  order:
    url: "http://localhost:12000"
